name: Build and Package

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags (e.g., v1.0.0)
  workflow_dispatch:  # Allow manual triggering

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        include:
          - os: windows-latest
            package-type: msi
            file-ext: msi
            jpackage-args: --win-menu --win-shortcut --win-dir-chooser
          - os: macos-latest
            package-type: pkg
            file-ext: pkg
            jpackage-args: --mac-package-identifier com.musimizer --mac-package-name "Musimizer"

    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'
    
    - name: Install WiX Toolset (Windows only)
      if: matrix.os == 'windows-latest'
      shell: pwsh
      run: |
        # Download WiX Toolset
        $wixUrl = "https://github.com/wixtoolset/wix3/releases/download/wix3112rtm/wix311.exe"
        $wixInstaller = "$env:RUNNER_TEMP\wix311.exe"
        
        # Download and install WiX
        Write-Host "Downloading WiX Toolset..."
        Invoke-WebRequest -Uri $wixUrl -OutFile $wixInstaller
        Write-Host "Installing WiX Toolset..."
        Start-Process -FilePath $wixInstaller -ArgumentList "/quiet" -Wait -NoNewWindow
        
        # Add WiX to PATH
        $wixPath = "${env:ProgramFiles(x86)}\WiX Toolset v3.11\bin"
        Add-Content -Path $env:GITHUB_PATH -Value $wixPath
        Write-Host "WIX_PATH=$wixPath" | Out-File -FilePath $env:GITHUB_ENV -Append
        Write-Host "WiX Toolset installed successfully"
        
    - name: Build with Maven
      run: mvn -B clean package -DskipTests -Djavafx.platform=${{ matrix.os == 'windows-latest' && 'win' || 'mac' }}
      
    - name: Create runtime image (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        jlink --module-path "$JAVA_HOME/jmods" \
              --add-modules java.base,java.desktop,javafx.controls,javafx.fxml,javafx.graphics,javafx.base \
              --output target/image \
              --strip-debug \
              --compress 2 \
              --no-header-files \
              --no-man-pages
              
    - name: Create runtime image (Windows)
      if: matrix.os == 'windows-latest'
      shell: pwsh
      run: |
        $jmods = "$env:JAVA_HOME\jmods"
        jlink --module-path $jmods `
              --add-modules java.base,java.desktop,javafx.controls,javafx.fxml,javafx.graphics,javafx.base `
              --output target/image `
              --strip-debug `
              --compress 2 `
              --no-header-files `
              --no-man-pages
              
    - name: Create installer (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout | sed 's/-SNAPSHOT$//')
        
        jpackage --name "Musimizer" \
                 --input target \
                 --main-jar "musimizer-${version}.jar" \
                 --main-class "com.musimizer.MainApp" \
                 --type "${{ matrix.package-type }}" \
                 --dest target/installer \
                 --runtime-image target/image \
                 --app-version "$version" \
                 --vendor "Musimizer" \
                 --copyright "Copyright $(date +'%Y')" \
                 ${{ matrix.jpackage-args }}
                 
    - name: Create installer (Windows)
      if: matrix.os == 'windows-latest'
      shell: pwsh
      run: |
        $version = (mvn help:evaluate -Dexpression=project.version -q -DforceStdout) -replace '-SNAPSHOT$',''
        
        # Ensure WiX is in PATH
        $env:Path = "$env:WIX_PATH;$env:Path"
        
        $jpackageArgs = @(
          "--name", "Musimizer",
          "--input", "target",
          "--main-jar", "musimizer-${version}.jar",
          "--main-class", "com.musimizer.MainApp",
          "--type", "${{ matrix.package-type }}",
          "--dest", "target/installer",
          "--runtime-image", "target/image",
          "--app-version", "$version",
          "--vendor", "Musimizer",
          "--copyright", "Copyright $(Get-Date -Format 'yyyy')"
        ) + ${{ matrix.jpackage-args }}.Split(" ")
        
        jpackage $jpackageArgs
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Musimizer-${{ matrix.os }}-${{ github.ref_name }}
        path: target/installer/*.${{ matrix.file-ext }}
        if-no-files-found: error