name: Native Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build Native Executables
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest]
        
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2-
        
    - name: Build with Maven
      run: mvn -B clean package -DskipTests
      
    - name: Build Native Image (Windows)
      if: runner.os == 'Windows'
      run: mvn -B gluonfx:build -Dgluonfx.target=host-win -DskipTests
      
    - name: Build Native Image (Mac)
      if: runner.os == 'macOS'
      run: mvn -B gluonfx:build -Dgluonfx.target=host-macos -DskipTests
      
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: native-executable-${{ runner.os }}
        path: |
          target/gluonfx/x86_64-windows/*.exe
          target/gluonfx/x86_64-macos/*
        if-no-files-found: error
